version: '3'

services:
  {{ project_name }}:
    restart: always
    image: registry.gitlab.com/{{ project_name }}/web-service
    command: gunicorn {{ project_name }}.wsgi:application --bind 0.0.0.0:8009 --workers 3 --log-level=DEBUG
    env_file: .env
    ports:
      - "8009:8009"
    expose:
      - "8000"
    networks:
    - {{ project_name }}_backend_tier

  celery:
    image: registry.gitlab.com/{{ project_name }}/web-service
    command: celery -A {{ project_name }} worker -l info
    env_file: .env
    restart: unless-stopped
    networks:
      - {{ project_name }}_backend_tier

  nginx:
    image: registry.gitlab.com/classmate2/web-service/nginx
    depends_on:
      - {{ project_name }}
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
      - "443"
    volumes:
      - ./logs/Nginx:/var/log/nginx/
    networks:
      - {{ project_name }}_backend_tier

volumes:
  static_volume:
    driver: local

networks:
  {{ project_name }}_backend_tier:
    driver: bridge
