version: '3'
services:
  db:
    image: postgres:14.0
    restart: always
    environment:
      - POSTGRES_USER={{project_name}}User
      - POSTGRES_PASSWORD={{project_name}}Password
    volumes:
      - {{ project_name }}_db_data:/var/lib/postgresql/data
    networks:
      - {{project_name}}_backend_tier
  redis:
    image: redis:latest
    restart: always
    networks:
      - {{ project_name }}_backend_tier

  {{ project_name }}:
    restart: always
    build: .
    depends_on:
      - db
      - redis
    env_file: .env
    command: python manage.py runserver 0.0.0.0:8009
    environment:
      - DJANGO_COLLECT_STATIC=off
      - DJANGO_MANAGEPY_MIGRATE=off
    links:
      - db:postgres
      - redis
    volumes:
      - .:/app
    ports:
      - "8009:8009"
    expose:
      - "8009"
    networks:
      - {{ project_name }}_backend_tier

  celery:
    restart: unless-stopped
    build: .
    env_file: .env
    command: celery -A {{project_name}} worker -l info
    depends_on:
      - db
      - redis
    networks:
      - {{ project_name }}_backend_tier
  beat:
    restart: unless-stopped
    build: .
    env_file: .env
    command: celery -A {{project_name}} beat -l info
    depends_on:
      - redis
    networks:
      - {{ project_name }}_backend_tier
  flower:
    image: mher/flower
    environment:
      - FLOWER_PORT=5555
      - CELERY_BROKER_URL=redis://redis:6379
    ports:
      - 5555:5555
    restart: unless-stopped
    expose:
      - "5555"
    depends_on:
      - redis
    networks:
      - {{ project_name }}_backend_tier


volumes:
  {{ project_name }}_db_data:
    driver: local
  static_volume:
    driver: local


networks:
  {{ project_name }}_backend_tier:
    driver: bridge
