version: '3'

services:
  db:
    restart: always
    image: postgres:14.0
    environment:
      - POSTGRES_USER={{ project_name }}User
      - POSTGRES_PASSWORD={{ project_name }}Password
    volumes:
      - "{{ project_name }}_db_data:/var/lib/postgresql/data"
    expose:
      - 5432
    ports:
      - 5433:5432
    networks:
      - {{ project_name }}_backend_tier

  redis:
    restart: always
    image: redis:latest
    networks:
      - {{ project_name }}_backend_tier

  {{ project_name }}:
    restart: always
    build: .
    depends_on:
      - redis
      - db
    env_file: .env
    command: gunicorn {{ project_name }}.wsgi:application --bind 0.0.0.0:8009 --workers 3 --log-level=DEBUG
    links:
      - db:postgres
      - redis
    ports:
      - "8009:8009"
    expose:
      - "8009"
    volumes:
      - .:/app
    networks:
    - {{ project_name }}_backend_tier

  celery:
    build: .
    command: celery -A {{ project_name }} worker -l info
    env_file: .env
    restart: unless-stopped
    depends_on:
      - db
      - redis
    networks:
      - {{ project_name }}_backend_tier

  nginx:
    build: ./nginx
    depends_on:
      - {{ project_name }}
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
      - "443"
    volumes:
      - ./nginx:/etc/nginx/conf.d/
      - ./static:/app/static/
      - ./media:/app/media/
      - ./logs/Nginx:/var/log/nginx/
    networks:
      - {{ project_name }}_backend_tier

volumes:
  {{ project_name }}_db_data:
    driver: local
  static_volume:
    driver: local

networks:
  {{ project_name }}_backend_tier:
    driver: bridge

